const type = {
    SET_ALL_COMPETITION: 'SET_ALL_COMPETITION',
    SET_COMPETITION: 'SET_COMPETITION',
    SET_REGISTERED_AND_NON_PARTICIPANTS: 'SET_REGISTERED_AND_NON_PARTICIPANTS',
}

export default type;