const type = {
    GET_CATEGORY_MODALITY_WITH_PART: 'GET_CATEGORY_MODALITY_WITH_PART',
    SET_PARTICIPANTS_COMPETITION_CATEGORY_MODALITY: 'SET_PARTICIPANTS_COMPETITION_CATEGORY_MODALITY',
    GET_ALL_ROUND_HEATS: 'GET_ALL_ROUND_HEATS',
    GET_ROUND_HEAT_DETAILS: 'GET_ROUND_HEAT_DETAILS',
}

export default type;